Next release (#12)
* Clean up transifex_pull

* Fix typo

* Update PsiCash lib to v1.4.2

* Fix typo

* Fix typo

* Clean up wording

Per translator feedback.

* Change placeholder style (to avoid translator confusion)

* Change DisableTimeouts functionality (#7)

* Change DisableTimeouts functionality

Instead of setting a long, fixed latency multiplier, DisableTimeouts now just
sets the random distribution to approximately uniformly select from the
default (or tactics configured) latency multiplier range.

The intent of this change is to avoid unnecessarily long timeouts that
resulted from users incorrectly checking this option, while still often trying
longer timeouts in case they are needed.

* Upgrade psiphon-tunnel-core to 9854fdf6

* Update next-release (#11)

* Fix Psiphon-Inc/psiphon-issues#603: Escape logs

* Fix cppcheck warnings

Specifically:

systemproxysettings.cpp:705:39: error: Uninitialized struct member: info.flags [uninitStructMember]
        o_originalProxyInfo.push_back(info);
                                      ^

logging.cpp:114:24: error: va_list 'args' was opened but not closed by va_end(). [va_end_missing]
    if (!buffer) return;
                       ^

* Replace uses of insecure lstrcpy

Fixes Psiphon-Inc/psiphon-issues#616

* Update translations